apiVersion: v1
kind: Service
metadata:
  name: app2-service
  #namespace: actividad-semana-6
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: app2
