apiVersion: v1
kind: Service
metadata:
  name: app3-service
  namespace: actividad-semana-6
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: app3
