version: '3'
services:
  app1:
    build: ./app1
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_URL=amqp://angelina:2162012@rabbitmq1:5672/

  rabbitmq1:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "angelina"
      RABBITMQ_DEFAULT_PASS: "2162012"
      RABBITMQ_NODENAME: "rabbit@rabbitmq1"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - "./data1:/var/lib/rabbitmq"
      - "./log1:/var/log/rabbitmq"
    networks:
      - mynetwork

  rabbitmq2:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq2"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "angelina"
      RABBITMQ_DEFAULT_PASS: "2162012"
      RABBITMQ_NODENAME: "rabbit@rabbitmq2"
    volumes:
      - "./data2:/var/lib/rabbitmq"
      - "./log2:/var/log/rabbitmq"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
